feat: update magento-api package 1.1.0 ->  2.1.1
vuestorefront/storefront-nuxt2-magento2 pull request #17
Opened 2023-08-17 12:06 UTC by bartoszherba

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSDoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

2023-08-17 12:27 UTC, Fifciu requested changes
We need to also update [the dedicated package.json](https://github.com/vuestorefront/storefront-nuxt2-magento2/blob/main/.vuestorefrontcloud/docker/middleware/package.json#L16) for the middleware which is only for the workflow.

2023-08-17 12:58 UTC, Fifciu approved these changes

2023-08-17 13:21 UTC, lukasborawski approved these changes

2023-08-18 07:15 UTC, WojtekTheWebDev approved these changes

2023-08-18 08:46 UTC, merged